#+title: Chapter 4

* Simplest version
:PROPERTIES:
:CREATED:  [2025-12-13 Sat 10:45]
:END:

#+begin_src c
  #include <stdio.h>

  static char input[2048];

  int main(int argc, char** argv) {
    puts("Lispy v0.0.1");
    puts("Press Ctrl+C to exit\n");
    while (1) {
      fputs("lispy> ", stdout);
      fgets(input, 2048, stdin);
      printf("No, you're a %s", input);
    }
  }
#+end_src

- ~puts~   writes a string to =stdout= and appends a newline.
- ~fputs~  writes a string to a given ~FILE*~ stream without appending a newline.
- ~printf~ writes formatted output to =stdout=.

* Preparing the use of a lib
:PROPERTIES:
:CREATED:  [2025-12-13 Sat 10:47]
:END:

We're going to use =libedit= on Linux, a lib that provides the
~readline~ and ~add_history~ functions. But we will not use the same
implementations of these two functions on Windows.

First, let's transform the original program to call the functions:

#+begin_src c
  #include <stdio.h>

  static char input[2048];

  char* readline(char* prompt) {
    fputs(prompt, stdout);
    fgets(input, 2048, stdin);
    return input;
  }

  void add_history(char* input) {}

  int main(int argc, char** argv) {
    puts("Lispy v0.0.1");
    puts("Press Ctrl+C to exit\n");
    while (1) {
      char* input = readline("lispy> ");
      add_history(input);
      printf("No, you're a %s", input);
    }
  }
#+end_src

Problems:

- =libedit='s ~readline~ will strip the final newline, unlike
  ~fgets~. So the newline must be added back. Our ~readline~ function
  doesn't strip the newline.

- Unlike ~fgets~, which writes to some existing buffer, =libedit='s
  readline function allocates new memory that must be freed with
  ~free~, from =stdlib=. If we call ~free~ on the input in the current
  code, it will fail.

Let's fix these problems so we can add the extra newline and call
~free~ on =input=, just like we will when using the library.

#+begin_src c
  #include <stdio.h>
  #include <stdlib.h>
  #include <string.h>

  static char buffer[2048];

  char* readline(char* prompt) {
    fputs(prompt, stdout);
    fgets(buffer, 2048, stdin);
    // Allocate buffer size + 1 byte for the null terminator
    char* cpy = malloc(strlen(buffer)+1);
    // Copy buffer in that memory space
    strcpy(cpy, buffer);
    // Replace the \n by \0 (there will be 2 null terminators and the second will
    // be useless I think)
    cpy[strlen(cpy)-1] = '\0';
    return cpy;
  }

  void add_history(char* input) {}

  int main(int argc, char** argv) {
    puts("Lispy v0.0.1");
    puts("Press Ctrl+C to exit\n");
    while (1) {
      char* input = readline("lispy> ");
      add_history(input);
      printf("No, you're a %s\n", input);
      free(input);
    }
  }
#+end_src

* Final version
:PROPERTIES:
:CREATED:  [2025-12-13 Sat 11:02]
:END:

=libedit= needs to be installed first:

#+begin_src sh
  sudo apt install libedit-dev
#+end_src

Then linked when compiling:

#+begin_src sh
  cc -std=c99 -Wall program.c -ledit -o program
#+end_src

Now we can conditionally include functionalities from =libedit=, only
on Linux.

#+begin_src c
  #include <stdio.h>
  #include <stdlib.h>

  #ifdef _WIN32
  #include <string.h>

  static char buffer[2048];

  char* readline(char* prompt) {
    fputs(prompt, stdout);
    fgets(buffer, 2048, stdin);
    char* cpy = malloc(strlen(buffer)+1);
    strcpy(cpy, buffer);
    cpy[strlen(cpy)-1] = '\0';
    return cpy;
  }

  void add_history(char* input) {}
  #else
  #include <editline/readline.h>
  #include <editline/history.h>
  #endif

  int main(int argc, char** argv) {
    puts("Lispy v0.0.1");
    puts("Press Ctrl+C to exit\n");
    while (1) {
      char* input = readline("lispy> ");
      add_history(input);
      printf("No, you're a %s\n", input);
      free(input);
    }
  }
#+end_src
