#+title: Chapter 5

* Compilation
:PROPERTIES:
:CREATED:  [2025-12-13 Sat 14:06]
:END:

I included =mpc= as a [[file:../lib/mpc/][submodule]]. Thus the command becomes, from the
root dir:

#+begin_src sh
  cc -std=c99 -Wall -Ilib/mpc chapter5/doge_code.c lib/mpc/mpc.c -o build/doge_code
#+end_src

* Having fun with grammars
:PROPERTIES:
:CREATED:  [2025-12-13 Sat 18:57]
:END:

** Common Lisp
:PROPERTIES:
:CREATED:  [2025-12-28 Sun 13:26]
:END:

This chapter made me think of [[https://norvig.github.io/paip-lisp/#/chapter2][chapter 2]] from Peter Norvig's Paradigms
of Artificial Intelligence Programming, in which we create a grammar
to generate text.

I used that code to generate a Doge grammar that is close to BYOL's
version.

You can check it [[https://github.com/alecigne/lisp-books/blob/master/paip/paip2/paip2.lisp][here]]. The grammar looks like this:

#+begin_src lisp
  (defparameter *doge-grammar*
    '((Doge -> Phrase+)
      (Phrase+ -> (Phrase) (Phrase Phrase+))
      (Phrase -> (Interjection? Adjective Noun))
      (Interjection? -> () (Interjection))
      (Interjection -> wow)
      (Adjective -> many so such very)
      (Noun -> lisp language book build c)))
#+end_src

Below is a generation of 10 "doges":

#+begin_example
  PAIP2> (loop repeat 10 collect (generate 'doge))
  ((SO LANGUAGE WOW SUCH BOOK)
   (WOW VERY BUILD WOW VERY BOOK VERY LANGUAGE)
   (WOW MANY LISP)
   (SO BUILD)
   (WOW VERY LISP)
   (WOW SUCH LISP)
   (SO BUILD)
   (SO BOOK)
   (WOW VERY LISP)
   (VERY LANGUAGE SUCH LANGUAGE))
#+end_example

Wow, so 2013.

** =nearley.js=
:PROPERTIES:
:CREATED:  [2025-12-28 Sun 13:26]
:END:

[[https://nearley.js.org/][Nearley]] is a JS parser. A playground is available [[https://omrelli.ug/nearley-playground/][here]] for parsing and
generation.

For the Doge grammar above:

#+begin_example
  doge -> phrase (", " phrase):*
  phrase -> (interjection " "):? adjective " " noun
  interjection -> "wow"
  adjective -> "many" | "so" | "such" | "very"
  noun -> "lisp" | "language" | "book" | "build" | "c"
#+end_example

Results:

#+begin_example
  wow so c, many lisp
  wow many build
  wow such c, wow such c, wow many lisp, such build, very lisp
  so build
#+end_example

* Bonus Marks
:PROPERTIES:
:CREATED:  [2025-12-14 Sun 15:48]
:END:

** Describe textually a grammar for decimal numbers
:PROPERTIES:
:CREATED:  [2025-12-14 Sun 15:49]
:END:

Well, the fun above is going to be very useful. We're going to
describe our grammar using the format from [[https://github.com/alecigne/lisp-books/blob/master/paip/paip2/paip2.lisp][PAIP chapter 2]].

Here it is:

#+begin_src lisp
  (defparameter *byol-decimal-grammar*
    '((Decimal  -> (Digits+ Dot Digits+))
      (Dot      -> ".")
      (Digits+  -> (Digit) (Digit Digits+))
      (Digit    -> "0" "1" "2" "3" "4" "5" "6" "7" "8" "9")))
#+end_src

We will add a very simple function to concatenate a list of strings,
since all our terminals in this grammar are strings:

#+begin_src lisp
  (defun generate-string (start)
    (apply #'concatenate 'string (generate start)))
#+end_src

Now let's use it to generate examples of our grammar:

#+begin_example
  PAIP2> (setf *grammar* *byol-decimal-grammar*)
  PAIP2> (loop repeat 10 collect (generate-string 'decimal))
  ("5.340" "41329.1" "7.80" "662.2" "7.20" "4.9" "91.31" "4.6" "28387.0" "13.7")
#+end_example

Pretty cool. Let's do it with Nearley:

#+begin_example
  decimal -> "-":? digit:+ dot digit:+
  dot -> "."
  digit -> [0-9]
#+end_example

Results:

#+begin_example
  59.2
  3623.46
  32318.4
  -83.10244
#+end_example

** Describe textually a grammar for web URLs
:PROPERTIES:
:CREATED:  [2025-12-14 Sun 15:55]
:END:

TODO 🙂

** Describe textually a grammar for simple English sentences
:PROPERTIES:
:CREATED:  [2025-12-14 Sun 15:56]
:END:

Already done in [[https://github.com/alecigne/lisp-books/blob/master/paip/paip2/paip2.lisp][PAIP2]]!
